---
repos:
  - repo: https://github.com/sirosen/fix-smartquotes
    rev: 0.1.1
    hooks:
      - id: fix-smartquotes
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.2.0
    hooks:
      - id: helm-docs
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint
        args: [-f, parsable]
